=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cmsmanagergroup/list-view.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="list-view">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="group" type="group" />
				<xs:element name="dynamicColumnProviders" type="dynamicColumnProviders" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="unassigned-group-name" type="xs:string" use="optional" />
			<xs:attribute name="allow-create-inline-items" type="xs:boolean" use="optional" />
			<xs:attribute name="header-popup-bean" type="xs:string" use="optional" />
		</xs:complexType>

	</xs:element>

	<xs:complexType name="group">
		<xs:sequence>
			<xs:element name="label" type="label" minOccurs="0" maxOccurs="unbounded" />
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element name="property" type="property" />
				<xs:element name="custom" type="custom" />
				<xs:element name="group" type="group" />
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="columnConfiguration" abstract="true">
		<xs:sequence>
			<xs:element name="renderer" type="cellRenderer" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="visible" type="xs:boolean" use="optional" default="false" />
		<xs:attribute name="sortable" type="xs:boolean" use="optional" default="false" />
		<xs:attribute name="editable" type="xs:boolean" use="optional" default="true" />
		<xs:attribute name="name" type="xs:string" use="optional" />
		<xs:attribute name="width" type="xs:string" use="optional" />
		<xs:attribute name="position" type="xs:positiveInteger" use="optional" default="1"/>
	</xs:complexType>

	<xs:complexType name="property">
		<xs:complexContent>
			<xs:extension base="columnConfiguration">
				<xs:sequence minOccurs="0" maxOccurs="1">
					<xs:element name="language" type="language" minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="parameter" type="parameter" minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
				<xs:attribute name="qualifier" type="xs:string" use="required" />
				<xs:attribute name="selectable" type="xs:boolean" use="optional" default="true" />
				<xs:attribute name="editor" type="xs:string" use="optional" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="custom">
		<xs:complexContent>
			<xs:extension base="columnConfiguration">
				<xs:sequence minOccurs="0" maxOccurs="1">
					<xs:element name="label" type="label" minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
				<xs:attribute name="class" type="xs:string" use="optional" />
				<xs:attribute name="spring-bean" type="xs:string" use="optional" />
				<xs:attribute name="selectable" type="xs:boolean" use="optional" default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="language">
		<xs:attribute name="isocode" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="parameter">
		<xs:sequence>
			<xs:element name="name" type="name" />
			<xs:element name="value" type="value" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="cellRenderer">
		<xs:attribute name="class" type="xs:string" use="optional" />
		<xs:attribute name="spring-bean" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:simpleType name="name">
		<xs:restriction base="xs:string" />
	</xs:simpleType>

	<xs:simpleType name="value">
		<xs:restriction base="xs:string" />
	</xs:simpleType>

	<xs:complexType name="label">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="key" use="optional" type="xs:string" />
				<xs:attribute name="lang" use="optional" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="dynamicColumnProviders">
		<xs:sequence>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element name="spring-bean" type="xs:string" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/listViewContentBrowserContext_ApparelSizeVariantProduct.xml
<?xml version="1.0" encoding="UTF-8"?>
<list-view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="list-view.xsd"
           unassigned-group-name="Other" allow-create-inline-items="true">
	<group name="General">
		<property qualifier="product.thumbnail" editor="simpleMediaReferenceSelector" visible="true">
			<renderer class="de.hybris.platform.cockpit.model.listview.impl.ImageCellRenderer"/>
		</property>
		<custom spring-bean="ProductContentBrowserStatusColumn" name="Status"
			visible="true" selectable="true">
			<label key="config.general.status" />
		</custom>
		<property qualifier="Product.code" visible="true" editable="false"/>
		<property qualifier="Product.name" visible="true" editable="false"/>
		<property qualifier="ApparelSizeVariantProduct.size" visible="true" editable="false"/>
	</group>
</list-view>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/listContentElementSection_AbstractCMSComponent.xml
<?xml version="1.0" encoding="UTF-8"?>
<list-view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="list-view.xsd"
           unassigned-group-name="Other">
	<group name="General">
		<custom spring-bean="CmsComponentIconColumn" name=" " visible="true" selectable="true" width="28px"/>
		<custom spring-bean="CmsComponentStatusColumn" name=" " visible="true" selectable="true" width="12px">
			<renderer class="de.hybris.platform.cmscockpit.components.listview.impl.CmsComponentStatusActionCellRenderer"/>
		</custom>
		<property qualifier="cmsitem.name" visible="true" width="130px">
			<renderer class="de.hybris.platform.cmscockpit.components.listview.impl.CmsComponentTextCellRenderer"/>
		</property>
		<custom spring-bean="CatalogAbstractContentElementSectionListActionColumn" name="Actions" visible="true" selectable="true" width="95px"/>
	</group>
</list-view>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/listViewContentBrowser_ContentPage.xml
<?xml version="1.0" encoding="UTF-8"?>
<list-view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="list-view.xsd"
           unassigned-group-name="Other">
	<group name="General">
		<custom class="de.hybris.platform.cockpit.services.config.impl.LineNumberColumn" name="Line nr" visible="false" selectable="true" width="70px"/>
		<property qualifier="cmsitem.name" visible="true" width="350px"/>
		<property qualifier="cmsitem.uid" visible="false"/>
		<property qualifier="cmsitem.catalogVersion" visible="false"  editor="shortListEditor"/>
		<property qualifier="abstractpage.defaultPage" visible="true" />
		<property qualifier="abstractpage.masterTemplate" visible="true"/>
		<property qualifier="ContentPage.label" visible="true"/>
		</group>
</list-view>
