=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/advanced-search.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="advanced-search">
	    <xs:complexType>
    		<xs:sequence>
    			<xs:element name="group" type="root-group" minOccurs="1" maxOccurs="1"/>
    			<xs:element name="related-types" minOccurs="0" maxOccurs="1" type="related-types"/>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:complexType name="group">
    	<xs:sequence>
    		<xs:element name="label" type="label" minOccurs="0" maxOccurs="unbounded"/>
    		<xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded"/>
    		<xs:element name="group" type="group" minOccurs="0" maxOccurs="unbounded"/>
    	</xs:sequence>
    	<xs:attribute name="name" type="xs:string" use="optional"/>
    	<xs:attribute name="visible" type="xs:boolean" use="optional" default="true"/>
    </xs:complexType>
  
     <xs:complexType name="root-group">
    	<xs:complexContent>
    		<xs:extension base="group">
				<xs:attribute name="type" type="xs:string" use="required"/>
				<xs:attribute name="excludeRootType" type="xs:boolean" use="optional" default="false"/>
				<xs:attribute name="includeSubTypes" type="xs:boolean" use="optional" default="true"/>
    		</xs:extension>    		
    	</xs:complexContent>	
    </xs:complexType>
  
  
  	<xs:complexType name="label">
    	<xs:simpleContent>
    		<xs:extension base="xs:string">
    			<xs:attribute name="key" use="optional" type="xs:string" />
				<xs:attribute name="lang" use="optional" type="xs:string" />
    		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="property">
    	<xs:sequence>
    		<xs:element name="conditions" type="conditionList" minOccurs="0" maxOccurs="1"/>
    		<xs:element name="parameter" type="parameter" minOccurs="0" maxOccurs="unbounded"/>
    	</xs:sequence>
    	<xs:attribute name="qualifier" type="xs:string" use="required"/>
    	<xs:attribute name="visible" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="sort-enabled" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="editor" type="xs:string" use="optional"/>
    </xs:complexType>  
    
    <xs:complexType name="related-types">
    	<xs:sequence>
    		<xs:element name="type" minOccurs="1" maxOccurs="unbounded" type="type"/>
    	</xs:sequence>
		<xs:attribute name="includeSubTypes" type="xs:boolean" use="optional" default="false"/>
    </xs:complexType>
    
    <xs:complexType name="type">
    	<xs:attribute name="code" type="xs:string" use="required"/>
    </xs:complexType>
    
    
    
    
    <xs:complexType name="conditionList">
    	<xs:sequence>
    		<xs:element name="condition" type="condition" minOccurs="1" maxOccurs="unbounded"/>
    	</xs:sequence>
    	<xs:attribute name="mode" type="mode" default="replace"/>
    </xs:complexType>
    
    <xs:simpleType name="mode">
    	<xs:restriction base="xs:string">
    		<xs:enumeration value="append"/>
    		<xs:enumeration value="replace"/>
    		<xs:enumeration value="exclude"/>
    	</xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="condition">
    	<xs:sequence>
    		<xs:element name="label" type="label" minOccurs="0" maxOccurs="unbounded"/>
    		<xs:element name="values" type="shortcutValueList" minOccurs="0" maxOccurs="1"/>
    	</xs:sequence>
    	<xs:attribute name="operator" type="xs:string" use="required"/>
    	<xs:attribute name="index" type="xs:integer" use="optional"/>
    </xs:complexType>
    
    <xs:complexType name="shortcutValueList">
    	<xs:sequence>
    		<xs:element name="value" type="shortcutValue" minOccurs="1" maxOccurs="unbounded"/>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="shortcutValue">
    	<xs:simpleContent>
    		<xs:extension base="xs:string">
    			<xs:attribute name="type" type="xs:string" default="java.lang.String"/>
    		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType name="parameter">
    	<xs:sequence>
    		<xs:element name="name" type="name"/>
    		<xs:element name="value" type="value"/>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="name">
    	<xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="value">
       	<xs:restriction base="xs:string"/> 
    </xs:simpleType>
    
</xs:schema>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/advancedSearch_AbstractPage.xml
<?xml version="1.0" encoding="UTF-8"?>
<advanced-search xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="advanced-search.xsd">
	
	<group name="root" type="abstractpage">
		<label key="config.general.searchfor" />
		<group name="general">
			<label key="cockpit.config.label.General" />
			<property qualifier="cmsitem.name" sort-enabled="true" visible="true"/>
			<property qualifier="cmsitem.uid" sort-enabled="true" visible="true"/>
			<property qualifier="cmsitem.catalogVersion" sort-enabled="true" visible="true"/>
			<property qualifier="abstractpage.defaultPage" sort-enabled="false"/>
			<property qualifier="abstractpage.masterTemplate" visible="false"/>
		</group>
		<group name="other">
			<label key="cockpit.config.label.Other" />
			<property qualifier="item.pk" sort-enabled="true" visible="false"/>
		</group>
	</group>
	
</advanced-search>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/advancedSearch_Product.xml
<?xml version="1.0" encoding="UTF-8"?>
<advanced-search xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="advanced-search.xsd">
	
	<group name="root" type="VariantProduct" excludeRootType="false">
		<label key="config.general.bmecat" />
		<group name="general">
			<label key="cockpit.config.label.General" />
			<property qualifier="product.code" sort-enabled="true">
				<conditions mode="append">
					<condition operator="between" index="1"/>
				</conditions>
			</property>
			<property qualifier="product.name" sort-enabled="true"/>
			<property qualifier="product.catalogversion" visible="false" />
			<property qualifier="product.approvalStatus" visible="false"/>
			<property qualifier="product.onlineDate" visible="false"/>
			<property qualifier="product.offlineDate" visible="false"/>
			<property qualifier="product.unit" visible="false" />
			<property qualifier="product.description" visible="true"/>
		</group>
		<group name="Price">
			<label key="config.general.prices" />
			<property qualifier="product.Europe1PriceFactory_PPG" visible="false"/>
			<property qualifier="product.Europe1PriceFactory_PTG" visible="false"/>
			<property qualifier="product.Europe1PriceFactory_PDG" visible="false"/>
			<property qualifier="product.minOrderQuantity" visible="false" sort-enabled="false"/>
			<property qualifier="product.maxOrderQuantity" visible="false" sort-enabled="false"/>
		</group>
		<group name="Category">
			<label key="config.general.categorysystem" />
			<property qualifier="product.supercategories" visible="false"/>
			<property qualifier="product.productReferences" visible="false"/>
		</group>
		<group name="Multimedia">
			<label key="config.general.multimedia" />
			<property qualifier="product.picture" visible="false"/>
			<property qualifier="product.thumbnail" visible="false"/>
			<property qualifier="product.data_sheet" visible="false"/>
			<property qualifier="product.detail" visible="false"/>
			<property qualifier="product.logo" visible="false"/>
			<property qualifier="product.normal" visible="false"/>
			<property qualifier="product.others" visible="false"/>
			<property qualifier="product.thumbnails" visible="false"/>
		</group>
		<group name="variants">
			<label key="config.general.variants" />
				<property qualifier="product.variants" visible="false" sort-enabled="false"/>
		</group>
		<group name="Additional">
			<label key="cockpit.config.label.Additional" />
			<property qualifier="product.ean" visible="false"/>
			<property qualifier="product.manufacturerAID" visible="false"/>
			<property qualifier="product.manufacturerName" visible="false"/>
			<property qualifier="product.deliveryTime" visible="false"/>
			<property qualifier="product.contentUnit" visible="false"/>
			<property qualifier="product.numberContentUnits" visible="false"/>
			<property qualifier="product.remarks" visible="false"/>
			<property qualifier="product.keywords" visible="false"/>
		</group>
		<group name="BMEcat">
			<label key="config.general.bmecat" />
			<property qualifier="product.manufacturertypeDescription" visible="false"/>
			<property qualifier="product.supplierAlternativeAID" visible="false"/>
			<property qualifier="product.erpGroupBuyer" visible="false"/>
			<property qualifier="product.erpGroupSupplier" visible="false"/>
			<property qualifier="product.segment" visible="false"/>
			<property qualifier="product.order" visible="false"/>
			<property qualifier="product.orderQuantityInterval" visible="false"/>
		</group>
	</group>
	
	<related-types includeSubTypes="false">
		<type code="VariantProduct" />
	</related-types>
	
</advanced-search>
