=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/base.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="base">
	    <xs:complexType>
    		<xs:sequence>
    			<xs:element name="search" type="search" minOccurs="0" maxOccurs="1"/>
    			<xs:element name="label" type="label" minOccurs="0" maxOccurs="1"/>
    			<xs:element name="initial-properties" type="initial-properties" minOccurs="0" maxOccurs="unbounded"/>
    			<xs:element name="default-property-settings" type="default-property-list" minOccurs="0" maxOccurs="1"/>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>

    <xs:complexType name="search">
    	<xs:sequence>
    		<xs:element name="search-properties" type="property-list" minOccurs="1" maxOccurs="1"/>
    		<xs:element name="sort-properties" type="property-list" minOccurs="0" maxOccurs="1"/>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="property-list">
    	<xs:sequence>
    		<xs:element name="property" type="property" minOccurs="1" maxOccurs="unbounded"/>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="default-property-list">
    	<xs:sequence>
    		<xs:element name="property" type="default-property" minOccurs="1" maxOccurs="unbounded"/>
    	</xs:sequence>
    </xs:complexType>
    
    
    <xs:complexType name="property">
		<xs:attribute name="qualifier" type="xs:string" use="required"/>
     </xs:complexType>    

	<xs:complexType name="default-property">
		<xs:sequence>
			<xs:element name="parameter" type="parameter" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="qualifier" type="xs:string" use="required"/>
		<xs:attribute name="defaultEditor" type="xs:string" use="optional"/>
		<xs:attribute name="baseProperty" type="xs:boolean" use="optional" default="true"/>
	</xs:complexType>

    <xs:complexType name="label">
    	<xs:sequence>
    		<xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded"/>
    	</xs:sequence>
    	<xs:attribute name="spring-bean" type="xs:string" use="optional"/>
    	<xs:attribute name="class" type="xs:string" use="optional"/>
    </xs:complexType>

	<xs:complexType name="initial-properties">
    	<xs:sequence>
    		<xs:element name="property-mapping" type="property-mapping" minOccurs="1" maxOccurs="unbounded"/>
    	</xs:sequence>
    	<xs:attribute name="source-object-template" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="property-mapping">
		<xs:attribute name="source" type="xs:string" use="required"/>
		<xs:attribute name="target" type="xs:string" use="required"/>
	</xs:complexType>
    
	<xs:complexType name="parameter">
    	<xs:sequence>
    		<xs:element name="name" type="name"/>
    		<xs:element name="value" type="value"/>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="name">
    	<xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="value">
       	<xs:restriction base="xs:string"/> 
    </xs:simpleType>
</xs:schema>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/base_TaxRow.xml
<?xml version="1.0" encoding="UTF-8"?>
<base xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="base.xsd">
	<search>
		<search-properties>
			<property qualifier="TaxRow.currency"/>
			<property qualifier="TaxRow.value"/>
		</search-properties>
		<sort-properties>
			<property qualifier="TaxRow.currency"/>
			<property qualifier="TaxRow.value"/>
		</sort-properties>
	</search>
	<label>
		<property qualifier="TaxRow.tax.name"/>
	</label>
</base>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/base_Media.xml
<?xml version="1.0" encoding="UTF-8"?>
<base xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="base.xsd">
	<search>
		<search-properties>
			<property qualifier="Media.code"/>
			<property qualifier="Media.altText"/>
			<property qualifier="Media.description"/>
		</search-properties>
		<sort-properties>
			<property qualifier="Item.modifiedtime"/>
			<property qualifier="Item.pk"/>
			<property qualifier="Media.code"/>
			<property qualifier="Media.altText"/>
			<property qualifier="Media.description"/>
		</sort-properties>
	</search>
	<label spring-bean="mediaLabelProvider"/>
	<initial-properties source-object-template="CMSItem">
		<property-mapping source="src.catalogVersion" target="Media.catalogVersion"/>
	</initial-properties>
	<initial-properties source-object-template="Product">
		<property-mapping source="src.catalogVersion" target="Media.catalogVersion"/>
	</initial-properties>
</base>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/base_Language.xml
<?xml version="1.0" encoding="UTF-8"?>
<base xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="base.xsd">
	<search>
		<search-properties>
			<property qualifier="Language.isocode"/>
			<property qualifier="Language.name"/>
		</search-properties>
		<sort-properties>
			<property qualifier="Item.modifiedtime"/>
			<property qualifier="Language.isocode"/>
			<property qualifier="Language.name"/>
		</sort-properties>
	</search>
	<label spring-bean="languageLabelProvider"/>
</base>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/base_WorkflowAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<base xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="base.xsd">
	<search>
		<search-properties>
			<property qualifier="WorkflowAction.code"/>
			<property qualifier="WorkflowAction.name"/>
		</search-properties>
		<sort-properties>
			<property qualifier="Item.modifiedtime"/>
			<property qualifier="WorkflowAction.code"/>
			<property qualifier="WorkflowAction.name"/>
		</sort-properties>
	</search>
	<label>
		<property qualifier="WorkflowAction.name"/>
	</label>
</base>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/base_Product.xml
<?xml version="1.0" encoding="UTF-8"?>
<base xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="base.xsd">
	<search>
		<search-properties>
			<property qualifier="Product.code"/>
			<property qualifier="Product.name"/>
			<property qualifier="Product.description"/>
			<property qualifier="Product.summary"/>
		</search-properties>
		<sort-properties>
			<property qualifier="Item.modifiedtime"/>
			<property qualifier="Product.code"/>
			<property qualifier="Product.name"/>
			<property qualifier="Product.description"/>
			<property qualifier="Item.pk"/>
		</sort-properties>
	</search>
	<label spring-bean="productLabelProvider"/>
</base>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/base_MediaContainer.xml
<?xml version="1.0" encoding="UTF-8"?>
<base xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="base.xsd">
	<search>
		<search-properties>
			<property qualifier="MediaContainer.qualifier"/>
			<property qualifier="MediaContainer.catalogVersion"/>
			<property qualifier="MediaContainer.name"/>
		</search-properties>
		<sort-properties>
			<property qualifier="MediaContainer.qualifier"/>
			<property qualifier="MediaContainer.catalogVersion"/>
			<property qualifier="MediaContainer.name"/>
		</sort-properties>
	</search>
	<label>
		<property qualifier="MediaContainer.qualifier"/>
	</label>
	<initial-properties source-object-template="Product">
		<property-mapping source="src.catalogVersion" target="MediaContainer.catalogVersion"/>
	</initial-properties>
</base>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/base_VariantProduct.xml
<?xml version="1.0" encoding="UTF-8"?>
<base xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="base.xsd">
	<search>
		<search-properties>
			<property qualifier="Product.code"/>
			<property qualifier="Product.name"/>
			<property qualifier="Product.description"/>
		</search-properties>
		<sort-properties>
			<property qualifier="Item.modifiedtime"/>
			<property qualifier="Item.pk"/>
			<property qualifier="Product.code"/>
			<property qualifier="Product.name"/>
			<property qualifier="Product.description"/>
		</sort-properties>
	</search>
	
	<label spring-bean="productLabelProvider"/>
	
	<initial-properties source-object-template="Product">
		<property-mapping source="src.catalogVersion" target="VariantProduct.catalogVersion"/>
		<property-mapping source="src" target="VariantProduct.baseProduct"/>
	</initial-properties>
</base>
