=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/editor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="editor">
	    <xs:complexType>
    		<xs:choice minOccurs="1" maxOccurs="unbounded">
    			<xs:element name="group" type="group"/>
    			<xs:element name="custom-group" type="custom-group"/>
    		</xs:choice>
    	</xs:complexType>
    </xs:element>

    <xs:complexType name="group">
    	<xs:sequence>
    		<xs:element name="label" type="label" minOccurs="0" maxOccurs="unbounded"/>
    		<xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded"/>
    	</xs:sequence>
    	<xs:attribute name="qualifier" type="xs:string" use="required"/>
    	<xs:attribute name="visible" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="tabbed" type="xs:boolean" use="optional" default="false"/>
    	<xs:attribute name="initially-opened" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="show-if-empty" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="show-in-create-mode" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="position" type="xs:positiveInteger" use="optional" default="1"/>
    	<xs:attribute name="printable" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="xmlDataProvider" type="xs:string" use="optional" default="xmlDataProvider"/>
    </xs:complexType>
    
    <xs:complexType name="custom-group">
    	<xs:sequence>
    		<xs:element name="label" type="label" minOccurs="0" maxOccurs="unbounded"/>
    	</xs:sequence>
    	<xs:attribute name="qualifier" type="xs:string" use="required"/>
    	<xs:attribute name="visible" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="class" type="xs:string" use="optional"/>
    	<xs:attribute name="spring-bean" type="xs:string" use="optional"/>
    	<xs:attribute name="initially-opened" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="show-if-empty" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="printable" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="xmlDataProvider" type="xs:string" use="optional" default="xmlDataProvider"/>
    </xs:complexType>
    
    <xs:complexType name="label">
    	<xs:simpleContent>
    		<xs:extension base="xs:string">
    			<xs:attribute name="key" use="optional" type="xs:string" />
    			<xs:attribute name="lang" use="optional" type="xs:string" />
    		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="property">
    	<xs:sequence>
    		<xs:element name="parameter" type="parameter" minOccurs="0" maxOccurs="unbounded"/>
    	</xs:sequence>
    	<xs:attribute name="qualifier" type="xs:string" use="required"/>
    	<xs:attribute name="visible" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="editor" type="xs:string" use="optional"/>
    	<xs:attribute name="printoutas" type="xs:string" use="optional"/>
    	<xs:attribute name="xmlDataProvider" type="xs:string" use="optional" default="xmlDataProvider"/>
    </xs:complexType> 
    
    <xs:complexType name="parameter">
    	<xs:sequence>
    		<xs:element name="name" type="name"/>
    		<xs:element name="value" type="value"/>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="name">
    	<xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="value">
       	<xs:restriction base="xs:string"/> 
    </xs:simpleType>
    
</xs:schema>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/editorArea_CMSCategoryRestriction.xml
<?xml version="1.0" encoding="UTF-8"?>
<editor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="editor.xsd">
	<group qualifier="General" visible="true" initially-opened="true">
		<label key="cockpit.config.label.General" />
		<property qualifier="cmsitem.name"/>
		<property qualifier="AbstractRestriction.description"/>
		<property qualifier="CMSCategoryRestriction.categories"/>
		<property qualifier="CMSCategoryRestriction.recursive"/>
		<property qualifier="cmsitem.uid"/>
		<property qualifier="cmsitem.catalogVersion" editor="shortListEditor"/>
	</group>

	<group qualifier="admin" visible="false" initially-opened="false">
		<label key="config.general.administration" />
		<property qualifier="Item.pk" />
		<property qualifier="Item.creationTime" />
		<property qualifier="Item.modifiedtime" />
		<property qualifier="AbstractRestriction.type"/>
		<property qualifier="AbstractRestriction.typeCode"/>
	</group>
	
	<custom-group 
		class="de.hybris.platform.cockpit.services.config.impl.UnassignedEditorSectionConfiguration" 
		qualifier="unassigned"
		initially-opened="false" visible="false">
		<label key="cockpit.config.label.Other" />
	</custom-group>
</editor>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/editorArea_DynamicBannerComponent.xml
<?xml version="1.0" encoding="UTF-8"?>
<editor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="editor.xsd">
	<group qualifier="General" visible="true" initially-opened="true">
		<label key="cockpit.config.label.General" />
		<property qualifier="CMSItem.name"/>
		<property qualifier="CMSItem.catalogVersion" editor="shortListEditor"/>
		<property qualifier="AbstractCMSComponent.visible"/>
	</group>

	<group qualifier="editorial" visible="true" initially-opened="false">
		<label key="config.general.editorial" />
		<property qualifier="AbstractBannerComponent.urlLink"/>
		<property qualifier="AbstractBannerComponent.external"/>
		<property qualifier="DynamicBannerComponent.mediaCodePattern"/>
		<property qualifier="AbstractBannerComponent.media" editor="simpleMediaReferenceSelector">
			<parameter>
				<name>mimeTypes</name>
				<value>image/jpeg;image/gif;image/png</value>
			</parameter>
			<parameter>
				<name>allowCreate</name>
				<value>true</value>
			</parameter>
			<parameter>
				<name>restrictToCreateTypes</name>
				<value>Media</value>
			</parameter>
			<parameter>
				<name>celumMediaFormat</name>
				<value>picture</value>
			</parameter>
			<parameter>
				<name>predefinedValuesStrategy</name>
				<value>imageMediaPredefinedValuesStrategy</value>
			</parameter>
		</property>
	</group>

	<group qualifier="visibility" visible="true" initially-opened="false">
		<label key="config.general.contextvisibility" />
		<property qualifier="AbstractCMSComponent.restrictions">
			<parameter>
				<name>allowCreate</name>
				<value>true</value>
			</parameter>
		</property>
		<property qualifier="AbstractCMSComponent.onlyOneRestrictionMustApply"/>
	</group>

	<group qualifier="admin" visible="true" initially-opened="false">
		<label key="config.general.administration" />
		<property qualifier="CMSItem.uid"/>
		<property qualifier="AbstractCMSComponent.slots"/>
		<property qualifier="AbstractCMSComponent.container"/>
		<property qualifier="Item.pk" />
		<property qualifier="Item.creationTime" />
		<property qualifier="Item.modifiedtime" />
	</group>
	
	<custom-group 
		class="de.hybris.platform.cockpit.services.config.impl.UnassignedEditorSectionConfiguration" 
		qualifier="unassigned"
		initially-opened="false"
		visible="false">
		<label key="cockpit.config.label.Other" />
	</custom-group>
</editor>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/editorArea_SearchBoxComponent.xml
<?xml version="1.0" encoding="UTF-8"?>
<editor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="editor.xsd">
	<group qualifier="General" visible="true" initially-opened="true">
		<label key="cockpit.config.label.General" />
		<property qualifier="CMSItem.name"/>
		<property qualifier="CMSItem.catalogVersion" editor="shortListEditor"/>
		<property qualifier="AbstractCMSComponent.visible"/>
	</group>

	<group qualifier="editorial" visible="true" initially-opened="false">
		<label key="config.general.editorial" />
		<property qualifier="SearchBoxComponent.displaySuggestions"/>
		<property qualifier="SearchBoxComponent.maxSuggestions"/>
		<property qualifier="SearchBoxComponent.displayProducts"/>
		<property qualifier="SearchBoxComponent.maxProducts"/>
		<property qualifier="SearchBoxComponent.displayProductImages"/>
		<property qualifier="SearchBoxComponent.minCharactersBeforeRequest"/>
		<property qualifier="SearchBoxComponent.waitTimeBeforeRequest"/>
	</group>

	<group qualifier="visibility" visible="true" initially-opened="false">
		<label key="config.general.contextvisibility" />
		<property qualifier="AbstractCMSComponent.restrictions">
			<parameter>
				<name>allowCreate</name>
				<value>true</value>
			</parameter>
		</property>
		<property qualifier="AbstractCMSComponent.onlyOneRestrictionMustApply"/>
	</group>

	<group qualifier="admin" visible="true" initially-opened="false">
		<label key="config.general.administration" />
		<property qualifier="CMSItem.uid"/>
		<property qualifier="AbstractCMSComponent.slots"/>
		<property qualifier="AbstractCMSComponent.container"/>
		<property qualifier="Item.pk" />
		<property qualifier="Item.creationTime" />
		<property qualifier="Item.modifiedtime" />
	</group>

	<custom-group
		class="de.hybris.platform.cockpit.services.config.impl.UnassignedEditorSectionConfiguration"
		qualifier="unassigned"
		initially-opened="false"
		visible="false">
		<label key="cockpit.config.label.Other" />
	</custom-group>
</editor>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/editorArea_PageTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<editor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="editor.xsd">
	<group qualifier="General" visible="true" initially-opened="true">
		<label key="cockpit.config.label.General" />
		<property qualifier="cmsitem.name"/>
		<property qualifier="cmsitem.uid"/>
		<property qualifier="cmsitem.catalogVersion" editor="shortListEditor"/>
		<property qualifier="AbstractCMSComponent.visible"/>
		<property qualifier="AbstractCMSComponent.type"/>
		<property qualifier="AbstractCMSComponent.typeCode"/>
		<property qualifier="AbstractCMSComponent.container"/>
		<property qualifier="pagetemplate.active"/>
		<property qualifier="pagetemplate.contentSlots"/>
	</group>

	<group qualifier="admin" visible="true" initially-opened="false">
		<label key="config.general.administration" />
		<property qualifier="Item.pk" />
		<property qualifier="Item.creationTime" />
		<property qualifier="Item.modifiedtime" />
	</group>
	
	<custom-group 
		class="de.hybris.platform.cockpit.services.config.impl.UnassignedEditorSectionConfiguration" 
		qualifier="unassigned"
		initially-opened="false">
		<label key="cockpit.config.label.Other" />
	</custom-group>
</editor>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/liveEditPreviewArea_PreviewData.xml
<?xml version="1.0" encoding="UTF-8"?>
<editor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="editor.xsd">
	<group qualifier="General">
		<label key="cockpit.config.label.General" />
		<property qualifier="PreviewData.user" />
		<property qualifier="PreviewData.userGroup" />
		<property qualifier="PreviewData.time">
			<parameter>
				<name>showExtrasMenu</name>
				<value>true</value>
			</parameter>
		</property>
		<property qualifier="PreviewData.language" editor="simple" />
		<property qualifier="PreviewData.page" />
		<property qualifier="PreviewData.uiExperience" editor="uiExperience" />
		<property qualifier="PreviewData.catalogVersions" editor="catalogVersionEditor" />
	</group>
</editor>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/editorArea_CMSRelation.xml
<?xml version="1.0" encoding="UTF-8"?>
<editor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="editor.xsd">
	<group qualifier="General" visible="true" initially-opened="true">
		<label key="cockpit.config.label.General" />
		<property qualifier="cmsrelation.uid"/>
		<property qualifier="cmsrelation.catalogVersion" editor="shortListEditor"/>
	</group>

	<group qualifier="admin" visible="true" initially-opened="false">
		<label key="config.general.administration" />
		<property qualifier="Item.pk" />
		<property qualifier="Item.creationTime" />
		<property qualifier="Item.modifiedtime" />
	</group>
	
	<custom-group 
		class="de.hybris.platform.cockpit.services.config.impl.UnassignedEditorSectionConfiguration" 
		qualifier="unassigned"
		initially-opened="false">
		<label key="cockpit.config.label.Other" />
	</custom-group>
</editor>
