=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/wizard-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="wizard-config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="displayed-properties" type="wizard-property-list" minOccurs="0" maxOccurs="1"/>
				<xs:element name="after-done-wizard-script" type="after-done-wizard-script" minOccurs="0" maxOccurs="1"/>    			
			</xs:sequence>
			<xs:attribute name="showPrefilledValues" type="xs:boolean" use="optional" default="false"/>
			<xs:attribute name="createMode" type="xs:boolean" use="optional" default="true"/>
			<xs:attribute name="selectMode" type="xs:boolean" use="optional" default="false"/>
			<xs:attribute name="displaySubtypes" type="xs:boolean" use="optional" default="true"/>
			<xs:attribute name="activateAfterCreate" type="xs:boolean" use="optional" default="false"/>
			<xs:attribute name="createWithinPopup" type="xs:boolean" use="optional" default="true"/>
			<xs:attribute name="createWithinEditor" type="xs:boolean" use="optional" default="true"/>
		</xs:complexType>
	</xs:element>	

	<xs:complexType name="wizard-property-list">
		<xs:sequence>
			<xs:element name="group" type="group" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="after-done-wizard-script">
		<xs:sequence>
			<xs:element name="content" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="language" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="property">
		<xs:sequence>
			<xs:element name="parameter" type="parameter" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="qualifier" type="xs:string" use="required"/>
		<xs:attribute name="editorCode" type="xs:string" use="optional"/>
		<xs:attribute name="visible" type="xs:boolean" use="optional" default="true"/>
	</xs:complexType>      
     
	<xs:complexType name="parameter">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="group">
    	<xs:sequence>
    		<xs:element name="label" type="label" minOccurs="1" maxOccurs="unbounded"/>
    		<xs:element name="property" type="property" minOccurs="1" maxOccurs="unbounded"/>
    	</xs:sequence>
    	<xs:attribute name="qualifier" type="xs:string" use="required"/>
    	<xs:attribute name="visible" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="tabbed" type="xs:boolean" use="optional" default="false"/>
    	<xs:attribute name="initially-opened" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="show-if-empty" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="show-in-create-mode" type="xs:boolean" use="optional" default="true"/>
    	<xs:attribute name="position" type="xs:positiveInteger" use="optional" default="1"/>
    </xs:complexType>
    
    <xs:complexType name="label">
    	<xs:simpleContent>
    		<xs:extension base="xs:string">
    			<xs:attribute name="key" use="optional" type="xs:string" />
				<xs:attribute name="lang" use="optional" type="xs:string" />
    		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>
	
	
</xs:schema>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/wizardConfig_RotatingImagesComponent.xml
<?xml version="1.0" encoding="UTF-8"?>
<wizard-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="wizard-config.xsd"
               showPrefilledValues="true" selectMode="true" createMode="true">
	<displayed-properties>
		<group qualifier="Base" visible="false" initially-opened="false">
			<label key="cockpit.config.label.General" />
			<property qualifier="RotatingImagesComponent.timeout" visible="false"/>
			<property qualifier="RotatingImagesComponent.effect" visible="false"/>
		</group>
		<group qualifier="Relations" visible="true">
			<label key="cmscockpit.Wizard.relations" />
			<property qualifier="RotatingImagesComponent.banners">
				<parameter name="predefinedValuesStrategy" value="cmsItemPredefinedValuesStrategy"/>
				<parameter name="allowCreate" value="true"/>
			</property>
			<property qualifier="AbstractCMSComponent.restrictions">
				<parameter name="allowCreate" value="true"/>
				<parameter name="excludeCreateTypes" value="CMSUserRestriction,CMSCategoryRestriction,CMSProductRestriction"/>
			</property>
		</group>
	</displayed-properties>
</wizard-config>

=== Adyen/adyen-hybris/bin/custom/adyen/adyencockpits/resources/adyencockpits-config/cockpitgroup/wizardConfig_Media.xml
<?xml version="1.0" encoding="UTF-8"?>
<wizard-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="wizard-config.xsd"
               showPrefilledValues="false" selectMode="true" createMode="true" createWithinPopup="false">
	<displayed-properties>
		<group qualifier="General" visible="true" initially-opened="true">
			<label key="cockpit.config.label.General" />
			<property qualifier="Media.code" />
			<property qualifier="Media.catalogVersion" editorCode="shortListEditor">
				<parameter name="autocomplete" value="false"/>
				<parameter name="autodrop" value="true"/>
				<parameter name="sclass" value="mediaUploadCatalogVersionCombo"/>
				<parameter name="constraint" value="strict"/>
			</property>
			<property qualifier="Media.mediaFormat" />
			<property qualifier="Media.folder" />
		</group>
	</displayed-properties>
</wizard-config>
