=== Adyen/adyen-hybris/adyenv6backoffice/resources/beans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 [y] hybris Platform

 Copyright (c) 2017 SAP SE or an SAP affiliate company.  All rights reserved.

 This software is the confidential and proprietary information of SAP
 ("Confidential Information"). You shall not disclose such Confidential
 Information and shall use it only in accordance with the terms of the
 license agreement you entered into with SAP.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="beans" type="abstractPojos" />

	<xs:complexType name="abstractPojos">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="bean" type="bean" />
			<xs:element name="enum" type="enum" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="abstractPojo" abstract="true">
		<xs:attribute name="class" type="xs:string" use="required" />
		<xs:attribute name="template" type="xs:string" use="optional" />
	</xs:complexType>



	<xs:complexType name="bean">
		<xs:complexContent>
			<xs:extension base="abstractPojo">
				<xs:sequence>
					<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="hints" type="hints" minOccurs="0" maxOccurs="1"/>
					<xs:element name="import" type="import" minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="annotations" type="annotations" minOccurs="0" maxOccurs="1"/>
					<xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
				<xs:attribute name="extends" type="xs:string" use="optional" />
				<xs:attribute name="type" type="xs:string" use="optional">
					<xs:annotation>
						<xs:documentation>Defines the type of bean. Allowed are 'bean' or 'event'.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
                <xs:attribute name="deprecated" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>Marks bean as deprecated. Allows defining a message.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
				<xs:attribute name="abstract" type="xs:boolean" use="optional" />
				<xs:attribute name="superEquals" type="xs:boolean" use="optional" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="hints">
		<xs:sequence>
			<xs:element name="hint" type="hint" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="hint">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="annotations">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="scope" use="optional" default="all">
		           <xs:simpleType>
		               <xs:restriction base="xs:NMTOKEN">
		                   <xs:enumeration value="all"/>
		                   <xs:enumeration value="getter"/>
		                   <xs:enumeration value="setter"/>
		                   <xs:enumeration value="member"/>
		               </xs:restriction>
		           </xs:simpleType>
		       </xs:attribute>        
		   </xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="import">
		<xs:attribute name="type" type="xs:string" use="required" />
		<xs:attribute name="static" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>

	<xs:complexType name="property">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="hints" type="hints" minOccurs="0" maxOccurs="1"/>
			<xs:element name="annotations" type="annotations" minOccurs="0" maxOccurs="3"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="type" type="xs:string" use="required" />
		<xs:attribute name="equals" type="xs:boolean" use="optional" />
		<xs:attribute name="deprecated" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Marks property as deprecated. Allows defining a message.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="enum">
		<xs:complexContent>
			<xs:extension base="abstractPojo">
				<xs:sequence>
					<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
				</xs:sequence>
                <xs:attribute name="deprecated" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>Marks bean as deprecated. Allows defining a message.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
</xs:schema>

=== Adyen/adyen-hybris/adyenv6b2ccheckoutaddon/resources/adyenv6b2ccheckoutaddon-beans.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
 [y] hybris Platform

 Copyright (c) 2000-2016 SAP SE or an SAP affiliate company.
 All rights reserved.

 This software is the confidential and proprietary information of SAP
 ("Confidential Information"). You shall not disclose such Confidential
 Information and shall use it only in accordance with the terms of the
 license agreement you entered into with SAP.
-->


<!--
	ATTENTION: This is just an example file. You have to edit it according to your needs.
-->

<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="beans.xsd">
	<bean class="de.hybris.platform.commercewebservicescommons.dto.order.PaymentDetailsWsDTO">
		<property name="encryptedCardNumber" type="String" />
		<property name="encryptedExpiryMonth" type="String" />
		<property name="encryptedExpiryYear" type="String" />
		<property name="encryptedSecurityCode" type="String" />
		<property name="saveCardData" type="Boolean" />
		<property name="adyenPaymentMethod" type="String" />
		<property name="adyenSelectedReference" type="String" />
		<property name="adyenSocialSecurityNumber" type="String" />
		<property name="adyenFirstName" type="String" />
		<property name="adyenLastName" type="String" />
	</bean>

	<bean class="de.hybris.platform.commercewebservicescommons.dto.order.AbstractOrderWsDTO">
		<property name="adyenBoletoUrl" type="String" />
		<property name="adyenBoletoData" type="String" />
		<property name="adyenBoletoExpirationDate" type="java.util.Date" />
		<property name="adyenBoletoDueDate" type="java.util.Date" />
	</bean>
</beans>

=== Adyen/adyen-hybris/bin/custom/adyen/adyenServices/resources/adyenServices-beans.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
 [y] hybris Platform

 Copyright (c) 2000-2013 hybris AG
 All rights reserved.

 This software is the confidential and proprietary information of hybris
 ("Confidential Information"). You shall not disclose such Confidential
 Information and shall use it only in accordance with the terms of the
 license agreement you entered into with hybris.
-->

<!--
	ATTENTION: This is just an example file. You have to edit it according to your needs.
-->

<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:util="http://www.springframework.org/schema/util"
       xsi:noNamespaceSchemaLocation="beans.xsd"
       xsi:schemaLocation="http://www.springframework.org/schema/util
       					   http://www.springframework.org/schema/util/spring-util.xsd">

	<bean class="com.adyen.facades.order.data.AdyenPaymentInfoData" extends="de.hybris.platform.commercefacades.order.data.CCPaymentInfoData">
		<property name="cardEncryptedJson" type="java.lang.String"/>
		<property name="shopperIp" type="java.lang.String"/>
		<property name="savePayment" type="boolean"/>
		<property name="recurringDetailReference" type="java.lang.String"/>
		<property name="installments" type="java.lang.String"/>
		<property name="useBoleto" type="boolean"/>
		<property name="boletoPaymentInfo" type="com.adyen.facades.order.data.BoletoPaymentData"/>
		<property name="useHPP" type="boolean"/>
		<property name="adyenPaymentBrand" type="java.lang.String"/>
		<property name="hppURL" type="java.lang.String"/>
		<property name="boletoPdfUrl" type="java.lang.String"/>
		<property name="issuerId" type="java.lang.String"/>
	</bean>
	
	<bean class="com.adyen.facades.order.data.BoletoPaymentData">
		<property name="firstName" type="java.lang.String"/>
		<property name="lastName" type="java.lang.String"/>
		<property name="selectedBrand" type="java.lang.String"/>
		<property name="socialSecurityNumber" type="java.lang.String"/>
		<property name="shopperStatement" type="java.lang.String"/>
	</bean>
	

</beans>
